server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: Cos1234!@#$

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 527734430644-t5d0h4kjb79o51stda4iplcs429dcu58.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 823611018725274
            client-secret: bcf86178e9bc06d5392d5a2da838943e
            scope:
            - email
            - public_profile
          naver:
            client-id: oJ6veZHM_g6F6vNe9JZc
            client-secret: Tj6Y1jDZaE
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버에서 보내줌